
trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- name: Deploykubemanifestsjava
  value: kube  

stages:
  - stage: Deploy
    displayName: Deploy stage
    jobs:
      - job: Deploykubemanifestsjava
        steps:
          
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)'
              artifact: 'manifests-02-Java-Apps'
              publishLocation: 'pipeline'
